# Generated by Django 4.1.3 on 2022-12-13 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsmodel',
            old_name='image',
            new_name='path',
        ),
    ]
