# Generated by Django 4.1.3 on 2022-12-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_image_productsmodel_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFormatsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='formats',
            field=models.ManyToManyField(to='shop.imageformatsmodel'),
        ),
    ]
